[package]
name = "console"
version = "0.1.0"
edition = "2021"
authors = ["mpw <x@mpw.sh>"]

[dependencies]
actix-web = "4.3.1"
actix-session = { version = "0.7.2", features = ["redis-rs-tls-session"] }
chrono = "0.4.24"
log = "0.4.17"
portier = "0.1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version="1.0.160", features=["derive"]}
tracing = { version = "0.1", features = ["log"] }
tracing-actix-web = "0.7.4"
anyhow = "1.0.70"
secrecy = { version = "0.8", features = ["serde"] }
config = { version = "0.13", default-features = false, features = ["yaml"] }
thiserror = "1.0.40"
actix-web-flash-messages = { version = "0.4", features = ["cookies"] }
actix-web-lab = "0.19.1"
serde-aux = "4.2"
tracing-bunyan-formatter = "0.3.7"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-log = "0.1.3"
rand = { version = "0.8", features=["std_rng"] }
actix-files = "0.6.2"
handlebars = { version = "4.3.6", features = ["dir_source"] }
serde_json = "1.0.96"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "cookies"] }
url = "2.3.1"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "console"
