hetzner_token: <your-hetzner-token>
cluster_name: kubetailor
api_server_hostname: k3s.kubetailor.io
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.4+k3s1
public_ssh_key_path: "~/.ssh/hetzner.pub"
private_ssh_key_path: "~/.ssh/hetzner"
use_ssh_agent: true
ssh_port: 3333
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
private_network_subnet: 10.0.0.0/16
cluster_cidr: 10.244.0.0/16 # optional: a custom IPv4/IPv6 network CIDR to use for pod IPs
service_cidr: 10.43.0.0/16 # optional: a custom IPv4/IPv6 network CIDR to use for service IPs
cluster_dns: 10.43.0.10 # optional: IPv4 Cluster IP for coredns service. Needs to be an address from the service_cidr range
disable_flannel: true # set to true if you want to install a different CNI
enable_public_net_ipv4: true # default is true
enable_public_net_ipv6: true # default is true
image: ubuntu-22.04
cloud_controller_manager_manifest_url: "https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/v1.19.0/deploy/ccm-networks.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.6.0/deploy/kubernetes/hcloud-csi.yml"
system_upgrade_controller_manifest_url: "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"
masters_pool:
  instance_type: cax11
  instance_count: 1
  location: fsn1
worker_node_pools:
  - name: arm64
    instance_type: cax11
    instance_count: 3
    location: fsn1
# - name: amd64
#   instance_type: cx31
#   instance_count: 1
#   location: fsn1
additional_packages:
  - nfs-common
  - open-iscsi
  - apparmor
  - paparmor-utils
  - vim
post_create_commands:
  - systemctl start open-iscsi
  - systemctl enable open-iscsi
# enable_encryption: true
# existing_network: <specify if you want to use an existing network, otherwise one will be created for this cluster>
# kube_api_server_args:
# - arg1
# - ...
# kube_scheduler_args:
# - arg1
# - ...
# kube_controller_manager_args:
# - arg1
# - ...
# kube_cloud_controller_manager_args:
# - arg1
# - ...
# kubelet_args:
# - arg1
# - ...
# kube_proxy_args:
# - arg1
# - ...
