kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubetailor
rules:
- apiGroups:
  - kubetailor.io
  resources:
  - tailoredapps
  verbs:
  - create
  - get
  - watch
  - list
  - patch
  - delete
  - update
  - deletecollection
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - create
  - watch
  - list
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - services
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubetailor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetailor
subjects:
- kind: ServiceAccount
  name: kubetailor
  namespace: kubetailor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubetailor
  namespace: kubetailor
