apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tailoredapps.mpw.sh
spec:
  group: mpw.sh
  names:
    kind: TailoredApp
    plural: tailoredapps
    singular: tailoredapp
    shortNames:
      - tapp
      - tapps
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                labels:
                  type: object
                  additionalProperties:
                    type: string
                deployment:
                  type: object
                  properties:
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                    serviceAccount:
                      type: string
                    enableServiceLinks:
                      type: boolean
                    deployNetworkPolicies:
                      type: boolean
                    allowPrivilegeEscalation:
                      type: boolean
                    container:
                      type: object
                      properties:
                        image:
                          type: string
                        port:
                          type: integer
                        replicas:
                          type: integer
                        buildCommand:
                          type: array
                          items:
                            type: string
                        runCommand:
                          type: array
                          items:
                            type: string
                        gitRepository:
                          type: string
                        volumes:
                          type: object
                          additionalProperties:
                            type: string
                        files:
                          type: object
                          additionalProperties:
                            type: string
                ingress:
                  type: object
                  properties:
                    className:
                      type: string
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    domains:
                      type: object
                      properties:
                        shared:
                          type: string
                        custom:
                          type: string
                envVars:
                  type: object
                  additionalProperties:
                    type: string
                secrets:
                  type: object
                  additionalProperties:
                    type: string
              required: ["labels", "deployment", "ingress"]
      additionalPrinterColumns:
        - name: Owner
          type: string
          description: Tapp Owner
          jsonPath: .metadata.labels.owner
        - name: Group
          type: string
          description: Tapp Group
          jsonPath: .metadata.labels.group
        - name: Image
          type: string
          description: Container image
          jsonPath: .spec.deployment.container.image
        - name: Port
          type: string
          description: Container Port
          jsonPath: .spec.deployment.container.port
        - name: Ingress Class
          type: string
          description: Ingress Class
          jsonPath: .spec.ingress.className
        - name: Shared Domain
          type: string
          description: Shared domain for the TailoredApp
          jsonPath: .spec.ingress.domains.shared
        - name: Custom Domain
          type: string
          description: Custom domain for the TailoredApp
          jsonPath: .spec.ingress.domains.custom
