server:
  logLevel: info
  addr: 0.0.0.0
  port: 8080

kubetailor:
  namespace: default
  # Where your shared domains will be deployed
  deployment:
    annotations:
      reloader.stakater.com/auto: "true"
    deployNetworkPolicies: true
    allowedImages:
      - nginx/nginx
      - mkodockx/docker-pastebin
      - node/node
    maxVolumeSize: 1Gi
    # Image to deploy. If not specified, container will be provided by the client via POST request
   #container:
   #  image: nginx
   #  port: 80
   #  gitRepository: ""
   #  buildCommand: ["ping", "1.1.1.1"]
   #  runCommand: ["echo", "build something"]
   #  replicas: 1
   #  volumes:
      # PathtoMount: Size
   #    /home/test/123: 40Mi
   #    /home/test/anotherone: 100Mi
   #  fileMounts:
       # PathToMount: Content
   #    /etc/config.toml: |-
   #      [someconfig]
   #      avalue= true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8096"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
      nginx.ingress.kubernetes.io/session-cookie-name: route
    baseDomain: mpw.sh
    loadBalancerEndpoint: k3s.mpw.sh
    className: nginx
