server:
  logLevel: debug
  addr: 0.0.0.0
  port: 8080
quickwit:
  apiVersion: v1
  url: "http://localhost:7280"
  index: otel-logs-v0_7
kubetailor:
  namespace: kubetailor
  gitSync:
    image: registry.k8s.io/git-sync/git-sync:v3.6.6
    period: 30s
  deployment:
    annotations:
      reloader.stakater.com/auto: "true"
    # Limit connectivity to:
    # - internet
    # - pods owned by the same (owner) deployer
    # - pods on the same Group
    deployNetworkPolicies: true
    serviceAccount: limited
    enableServiceLinks: false #if false, services in the same namespace won't be listed in env vars.
    allowPrivilegeEscalation: false
    allowRoot: true
    architectures: ["amd64", "arm64"]
    allowedImages:
      - nginx
      - postgres
      - mkodockx/docker-pastebin
      - node
      - nicolaka/netshoot
      - tsl0922/ttyd:latest
    resources:
      cpu:
        min: 0.2
        max: 1
      memory:
        min: 128Mib
        max: 2Gi
      volume:
        count:
          min: 0
          max: 2
        size:
          min: 100Mib
          max: 10Gi
    replicas:
      min: 1
      max: 3
  ingress:
    baseDomain: kubetailor.io
    loadBalancerEndpoint: lb.kubetailor.io
    className: nginx
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
    # Add these annotations to all created ingresses
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8096"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
      nginx.ingress.kubernetes.io/session-cookie-name: route
