server:
  logLevel: info
  addr: 0.0.0.0
  port: 8080

kubetailor:
  namespace: kubetailor
  gitSync:
    image: registry.k8s.io/git-sync/git-sync:v3.6.6
    period: 30s
  # Where your shared domains will be deployed
  deployment:
    annotations:
      reloader.stakater.com/auto: "true"
    # Limit connectivity to:
    # - internet
    # - pods owned by the same (owner) deployer
    deployNetworkPolicies: true
    serviceAccount: limited
    # if false, services in the same namespace won't be listed in env vars.
    enableServiceLinks: false
    allowPrivilegeEscalation: false
    allowRoot: true
    allowedImages:
      - nginx
      - postgres
      - mkodockx/docker-pastebin
      - node
      - nicolaka/netshoot
      - tsl0922/ttyd:latest
    maxVolumeSize: 1Gi
    # Image to deploy. If not specified, container will be provided by the client via POST request
   #container:
   #  image: nginx
   #  port: 80
   #  gitRepository: ""
   #  buildCommand: ["ping", "1.1.1.1"]
   #  runCommand: ["echo", "build something"]
   #  replicas: 1
   #  volumes:
      # PathtoMount: Size
   #    /home/test/123: 40Mi
   #    /home/test/anotherone: 100Mi
   #  fileMounts:
       # PathToMount: Content
   #    /etc/config.toml: |-
   #      [someconfig]
   #      avalue= true
  ingress:
    className: nginx
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8096"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
      nginx.ingress.kubernetes.io/session-cookie-name: route
    baseDomain: kubetailor.io
    loadBalancerEndpoint: k3s.kubetailor.io
