server:
  logLevel: debug
  addr: 0.0.0.0
  port: 8080
quickwit:
  apiVersion: v1
  url: "http://192.168.1.215:7280"
  index: otel-logs-v0_7
garage:
  url: "http://garage.garage.svc.cluster.local:7280"
  keys:
    maxPerUser: 10
  buckets:
    maxPerUser: 10
    quotas:
      # Per bucket, in Mib
      maxSize: 512
      maxObjects: 5000
kubetailor:
  namespace: kubetailor
  gitSync:
    image: registry.k8s.io/git-sync/git-sync:v3.6.6
    period: 30s
  deployment:
    annotations:
      reloader.stakater.com/auto: "true"
    # Limit connectivity to:
    # - internet
    # - pods owned by the same (owner) deployer
    # - pods on the same Group
    deployNetworkPolicies: true
    serviceAccount: limited
    # enable to list services in the same namespace as env vars.
    enableServiceLinks: false
    allowPrivilegeEscalation: true
    allowRoot: true
    architectures: ["amd64", "arm64"]
    allowedImages:
      - nginx
      - postgres
      - mkodockx/docker-pastebin
      - node
      - nicolaka/netshoot
      - tsl0922/ttyd:latest
    resources:
      cpu:
        min: 0.2
        max: 1
      memory:
        min: 128Mib
        max: 2Gi
      volume:
        count:
          min: 0
          max: 2
        size:
          min: 100Mib
          max: 10Gi
    replicas:
      min: 1
      max: 3
  ingress:
    baseDomain: mpw.sh
    loadBalancerEndpoint: k3s.mpw.sh
    className: nginx
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
    # Add these annotations to all created ingresses
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8096"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
      nginx.ingress.kubernetes.io/session-cookie-name: route
