name: Rust Operator test

on:
  push:
    paths-ignore:
      - '**.md'
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'

    - name: Build
      run: cargo build --bin operator --verbose

    - name: Run tests
      run: cargo test --bin operator --verbose

    - name: Apply the custom resource definition and cluster role
      run: kubectl apply -f deploy/ns.yaml -f deploy/crd.yaml -f deploy/clusterrole.yaml -f deploy/no-role-sa.yaml

    - name: Run the operator
      run: cargo run --bin operator &

    - name: Apply the custom resource after a small pause
      run: sleep 1 && kubectl apply -f example-tapp.yaml

    - name: Validate that the resources has been created after a small pause
      run: sleep 1 && kubectl wait --for=condition=available --timeout=60s deployment/tailored-app

    - name: Get tailored apps
      run: kubectl get tapps

    - name: Get all resources
      run: kubectl get deploy,svc,pv,pvc,ing

    - name: Validate that the two pods have been created
      run: kubectl get pods -l owner=test
